### ISSUE TITLE
Fix overlapping annotations problem

### ISSUE THREAD

**Issue by edsfocci** [bill-tracker/bill-tracker#171]
When I insert 4 or more annotations, and I reload, the right-side bar tends to overlap some of the annotations, making much of it unreadable.

When I save 4 annotations:
![weird_annotation_problem-before](https://cloud.githubusercontent.com/assets/1051322/8770809/b4a3d4b8-2e7d-11e5-939f-3323a2187241.png)

After I reload:
![weird_annotation_problem-after](https://cloud.githubusercontent.com/assets/1051322/8770812/bdb16340-2e7d-11e5-8192-581791df1c4f.png)

**Comment by mcdermottsolutions** [comment]
I should probably grab this one.  After the homepage landing page is done, this will be top priority for me.

**Comment by mcdermottsolutions** [comment]
I think this is fixed now.
