### ISSUE TITLE
Create a billtracker namecheap account

### ISSUE THREAD

**Issue by mcdermottsolutions** [bill-tracker/bill-tracker#173]
Ok next steps on this are:
~~1) adding billtracker.org to our heroku custom domains and setting the domain's DNS to our custom heroku DNS in namecheap.com - Ed, if you can do the first part of this, I can do the second once I have the DNS info https://devcenter.heroku.com/articles/custom-domains~~ Done - thanks Ed!
2) Me creating a namecheap account just for our domain and transferring our domain there, so we can all have login/pass to it.  I was a dummy and registered it in my personal namecheap.com account, sorry.  I'll work on this one over the next couple days.

**Comment by edsfocci** [comment]
I believe this is already done?

**Comment by mcdermottsolutions** [comment]
Created a new namecheap account & moved domain there.
