### ISSUE TITLE
Hide Search button on bills page.

### ISSUE THREAD

**Issue by deeptiboddapati** [bill-tracker/bill-tracker#221]
Since it doesn't work, and its not in mvp would you mind removing it/hiding it

**Comment by deeptiboddapati** [comment]
Since it doesn't work, and its not needed in mvp please remove it/hide it.

**Comment by mcdermottsolutions** [comment]
Search is hidden on bills page now.
https://billtracker-dev.herokuapp.com/bills/SB10/
